# Basic
title: Lloyd's Kōdo Sekai
subtitle: no subtitle
welcome_message: no welcome_message
description: no description
creator: <a href="http://onev.cat">@onevcat</a>

# url: ""
avatar_img: "/assets/images/avatar.jpg"
background_cover: "/assets/images/background-cover.jpg"

post_img_dir: "/assets/images/post/"

permalink: /blog/:year/:month/:day/:title.html

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}


# Plugins
plugins:
    - jekyll-seo-tag

# Pagination
gems: [jekyll-paginate, jekyll-seo-tag]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: lloydscodeworld
    # duoshuo: 
    
# Social
social:
    facebook: lloyd.fung.180
    # weibo: onevcat
    github: LloydFung
    # twitter: onevcat
    gplus: 116499878994678505080
    mail: lloydfung@centamail.com
    linkedin: lloyd-fung-13a8b311a

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host